<?php require_once 'config/auth.php'; checkAuth(); ?>
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Студенческий портал</title><link rel="stylesheet" href="public/style.css"></head><body>
<header class="top-header"><div class="brand-block"><div class="brand-mark">🎓</div><div><h1>Студенческий портал</h1><p>Учёт студентов, групп, предметов, оценок и посещаемости</p></div></div><div class="user-panel"><span class="user-chip"><?php echo htmlspecialchars($_SESSION['full_name']); ?> · <?php echo htmlspecialchars($_SESSION['role_name']); ?></span><a href="logout.php" class="logout-btn">Выйти</a></div></header>
<main class="layout"><aside class="sidebar">
<button class="nav-btn active" data-section="groups" onclick="showSection('groups', this)"><span class="nav-emoji">🏫</span><span><strong>Группы</strong><small>Учебные группы</small></span></button>
<button class="nav-btn" data-section="students" onclick="showSection('students', this)"><span class="nav-emoji">👨‍🎓</span><span><strong>Студенты</strong><small>Данные студентов</small></span></button>
<button class="nav-btn" data-section="teachers" onclick="showSection('teachers', this)"><span class="nav-emoji">👩‍🏫</span><span><strong>Преподаватели</strong><small>Список преподавателей</small></span></button>
<button class="nav-btn" data-section="subjects" onclick="showSection('subjects', this)"><span class="nav-emoji">📘</span><span><strong>Предметы</strong><small>Дисциплины</small></span></button>
<button class="nav-btn" data-section="grades" onclick="showSection('grades', this)"><span class="nav-emoji">📝</span><span><strong>Оценки</strong><small>До 5 баллов</small></span></button>
<button class="nav-btn" data-section="attendance" onclick="showSection('attendance', this)"><span class="nav-emoji">📆</span><span><strong>Посещаемость</strong><small>Занятия</small></span></button>
<button class="nav-btn" data-section="logs" onclick="showSection('logs', this)"><span class="nav-emoji">📋</span><span><strong>Журнал</strong><small>Действия</small></span></button>
</aside><section class="content">
<div id="groups" class="section"><div class="section-head"><h2>Учебные группы</h2><p>Добавление и просмотр групп студентов.</p></div><form id="groupForm" class="form-grid"><input type="text" id="groupName" placeholder="Название группы" required><input type="number" id="groupCourse" placeholder="Курс" min="1" max="6" required><input type="text" id="groupSpecialty" placeholder="Специальность"><button type="submit">Добавить группу</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>Группа</th><th>Курс</th><th>Специальность</th><th>Действие</th></tr></thead><tbody id="groupsTable"></tbody></table></div></div>
<div id="students" class="section hidden"><div class="section-head"><h2>Студенты</h2><p>Карточки студентов и распределение по группам.</p></div><form id="studentForm" class="form-grid"><select id="studentGroupId" required></select><input type="text" id="studentFullName" placeholder="ФИО" required><input type="date" id="studentBirthDate"><input type="email" id="studentEmail" placeholder="Email"><input type="text" id="studentPhone" placeholder="Телефон"><input type="text" id="studentAddress" placeholder="Адрес"><input type="number" id="studentAdmissionYear" placeholder="Год поступления" min="2000" max="2100"><button type="submit">Добавить студента</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>ФИО</th><th>Группа</th><th>Дата рождения</th><th>Email</th><th>Телефон</th><th>Адрес</th><th>Год</th><th>Действие</th></tr></thead><tbody id="studentsTable"></tbody></table></div></div>
<div id="teachers" class="section hidden"><div class="section-head"><h2>Преподаватели</h2><p>Преподавательский состав.</p></div><form id="teacherForm" class="form-grid"><input type="text" id="teacherFullName" placeholder="ФИО" required><input type="email" id="teacherEmail" placeholder="Email"><input type="text" id="teacherPhone" placeholder="Телефон"><input type="text" id="teacherDepartment" placeholder="Кафедра"><button type="submit">Добавить преподавателя</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>ФИО</th><th>Email</th><th>Телефон</th><th>Кафедра</th><th>Действие</th></tr></thead><tbody id="teachersTable"></tbody></table></div></div>
<div id="subjects" class="section hidden"><div class="section-head"><h2>Предметы</h2><p>Учебные дисциплины.</p></div><form id="subjectForm" class="form-grid"><select id="subjectTeacherId"></select><input type="text" id="subjectName" placeholder="Название предмета" required><input type="number" id="subjectHours" placeholder="Количество часов" min="0"><input type="number" id="subjectSemester" placeholder="Семестр" min="1" max="12"><button type="submit">Добавить предмет</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>Предмет</th><th>Преподаватель</th><th>Часы</th><th>Семестр</th><th>Действие</th></tr></thead><tbody id="subjectsTable"></tbody></table></div></div>
<div id="grades" class="section hidden"><div class="section-head"><h2>Оценки</h2><p>Оценки студентов по пятибалльной системе.</p></div><form id="gradeForm" class="form-grid"><select id="gradeStudentId" required></select><select id="gradeSubjectId" required></select><input type="number" id="gradeValue" placeholder="Оценка от 1 до 5" min="1" max="5" required><input type="date" id="gradeDate" required><input type="text" id="gradeComment" placeholder="Комментарий"><button type="submit">Добавить оценку</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>Студент</th><th>Предмет</th><th>Оценка</th><th>Дата</th><th>Комментарий</th><th>Действие</th></tr></thead><tbody id="gradesTable"></tbody></table></div></div>
<div id="attendance" class="section hidden"><div class="section-head"><h2>Посещаемость</h2><p>Учёт посещений и пропусков занятий.</p></div><form id="attendanceForm" class="form-grid"><select id="attendanceStudentId" required></select><select id="attendanceSubjectId" required></select><input type="date" id="attendanceDate" required><select id="attendanceStatus"><option value="present">Присутствовал</option><option value="absent">Отсутствовал</option><option value="late">Опоздал</option></select><input type="text" id="attendanceComment" placeholder="Комментарий"><button type="submit">Добавить посещаемость</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>Студент</th><th>Предмет</th><th>Дата</th><th>Статус</th><th>Комментарий</th><th>Действие</th></tr></thead><tbody id="attendanceTable"></tbody></table></div></div>
<div id="logs" class="section hidden"><div class="section-head"><h2>Журнал действий</h2><p>История операций в системе.</p></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Пользователь</th><th>Email</th><th>Действие</th><th>Дата</th></tr></thead><tbody id="logsTable"></tbody></table></div></div>
</section></main><script src="public/app.js"></script></body></html>
